### ISSUE TITLE
MariaDB Unix-socket plugin not loaded 문제 발생(DB로그인 불가)

### ISSUE THREAD

**Issue by yeom-heesu** [BJ-Lim/Capstone_Design#12]
1.  데몬으로 돌고있는 마리아 DB를 중단
sudo service mariadb stop
2. 로그인 인증 우회
sudo mysqld_safe --skip-grant-tables &
3. mariaDB 재접속
mysql -u root

**Comment by ByoungJoonIm** [comment]
해결 완료되었으며 Trouble shooting 문서로 이관되었습니다.
