### ISSUE TITLE
[Dmoj]judge 까지 올렸지만 웹이 작동을 안함

### ISSUE THREAD

**Issue by jjxxmiin** [BJ-Lim/Capstone_Design#4]
502 Bad Gateway

**Comment by ByoungJoonIm** [comment]
리눅스 쉘에 다음 명령을 입력하면 어디에 문제가 있는지 참고할 수 있습니다.

tail -30 /var/log/nginx/error.log

**Comment by ByoungJoonIm** [comment]
다음 명령을 통해 재시도 후 정상적으로 작동하는 것을 확인할 수 있습니다.

docker stop dmoj-site
docker rm dmoj-site
docker run -d -it --name dmoj-site -p 80:80 schoj/site /bin/bash

위 명령을 모두 실행한 후 약 1분후 다시 시작합니다.
